// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import { IERC20 } from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import { SafeERC20 } from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import { ReentrancyGuard } from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import { Pausable } from "@openzeppelin/contracts/utils/Pausable.sol";
import { Ownable } from "@openzeppelin/contracts/access/Ownable.sol";
import { IYieldStrategy } from "./interfaces/IYieldStrategy.sol";

/// @title GivvestVault
/// @notice No-loss charity yield vault. Users deposit USDC; principal is always fully withdrawable.
///         Yield generated by the strategy (Aave V3) is harvested and sent to GivvestTreasury
///         for charitable distribution by the DAO.
///
/// @dev Yield attribution uses a global accumulator (like Synthetix StakingRewards / MasterChef)
///      scaled at 1e27 to handle 6-decimal USDC precisely.
///
contract GivvestVault is ReentrancyGuard, Pausable, Ownable {
    using SafeERC20 for IERC20;

    // -------------------------------------------------------------------------
    // State
    // -------------------------------------------------------------------------

    IERC20 public immutable usdc;
    IYieldStrategy public strategy;
    address public treasury;

    /// @notice Each user's deposited principal (USDC, 6 decimals).
    mapping(address => uint256) public principalOf;

    /// @notice Sum of all principalOf values.
    uint256 public totalPrincipal;

    // --- Per-user donation accumulator ---
    // All yield is destined for charity, so a user's donation share equals
    // their proportional share of all yield that accrued while they held principal.

    /// @notice Cumulative donated USDC per unit of principal, scaled by 1e27.
    uint256 public accDonatedPerPrincipal;

    /// @notice Yield that has been attributed in the accumulator but not yet physically
    ///         swept from Aave to the treasury (still earning interest in Aave).
    uint256 public bookedInAave;

    /// @notice Each user's snapshot of accDonatedPerPrincipal at their last settle.
    mapping(address => uint256) public donationCheckpoint;

    /// @notice Cumulative donated USDC settled for each user.
    mapping(address => uint256) public donatedRealized;

    // Minimum harvestable amount to avoid dust transfers (1 USDC = 1e6).
    uint256 public constant MIN_HARVEST = 1e6;

    // -------------------------------------------------------------------------
    // Events
    // -------------------------------------------------------------------------

    event Deposited(address indexed user, uint256 amount, uint256 timestamp);
    event Withdrawn(address indexed user, uint256 amount, uint256 timestamp);
    event Harvested(uint256 amount, uint256 treasuryBalanceAfter);
    event StrategySet(address indexed oldStrategy, address indexed newStrategy);
    event TreasurySet(address indexed oldTreasury, address indexed newTreasury);

    // -------------------------------------------------------------------------
    // Errors
    // -------------------------------------------------------------------------

    error ZeroAmount();
    error ZeroAddress();
    error ExceedsPrincipal(uint256 requested, uint256 available);
    error BelowMinHarvest();
    error StrategyInsolvent();
    error NewStrategyInsolvent();

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    /// @param _usdc      USDC token address on this chain.
    /// @param _strategy  Initial yield strategy (AaveV3Strategy).
    /// @param _treasury  GivvestTreasury address.
    /// @param _owner     Initial owner (transferred to admin wallet on live deploy).
    constructor(address _usdc, address _strategy, address _treasury, address _owner) Ownable(_owner) {
        if (_usdc == address(0) || _strategy == address(0) || _treasury == address(0)) revert ZeroAddress();
        usdc = IERC20(_usdc);
        strategy = IYieldStrategy(_strategy);
        treasury = _treasury;
    }

    // -------------------------------------------------------------------------
    // Internal accounting helpers
    // -------------------------------------------------------------------------

    /// @dev Books newly accrued yield (since last accrue) into the global accumulator.
    ///      Must be called before any principal change so yield is credited to those who earned it.
    function _accrue() internal {
        if (totalPrincipal == 0) return;
        uint256 assets = strategy.totalAssets();
        // Guard against rounding where assets < totalPrincipal + bookedInAave.
        if (assets <= totalPrincipal + bookedInAave) return;
        uint256 newYield = assets - totalPrincipal - bookedInAave;
        if (newYield == 0) return;
        accDonatedPerPrincipal += (newYield * 1e27) / totalPrincipal;
        bookedInAave += newYield;
    }

    /// @dev Settles pending yield attribution for `user` into donatedRealized.
    ///      Calls _accrue() first to capture any unbooked yield before the principal changes.
    function _settle(address user) internal {
        _accrue();
        uint256 pending = (principalOf[user] * (accDonatedPerPrincipal - donationCheckpoint[user])) / 1e27;
        donatedRealized[user] += pending;
        donationCheckpoint[user] = accDonatedPerPrincipal;
    }

    // -------------------------------------------------------------------------
    // User-facing functions
    // -------------------------------------------------------------------------

    /// @notice Deposit USDC into the vault. Caller must approve this contract first.
    /// @param amount Amount of USDC to deposit (6 decimals). Must be > 0.
    function deposit(uint256 amount) external nonReentrant whenNotPaused {
        if (amount == 0) revert ZeroAmount();
        _settle(msg.sender);

        // Effects first: update principal before the external interaction.
        principalOf[msg.sender] += amount;
        totalPrincipal += amount;

        // Interactions: pull USDC from user, then forward to strategy.
        usdc.safeTransferFrom(msg.sender, address(this), amount);
        usdc.forceApprove(address(strategy), amount);
        strategy.deposit(amount);

        emit Deposited(msg.sender, amount, block.timestamp);
    }

    /// @notice Withdraw USDC principal. Capped at principalOf[msg.sender].
    ///         Works even when the vault is paused.
    /// @param amount Amount of USDC to withdraw (6 decimals). Must be <= principalOf[msg.sender].
    function withdraw(uint256 amount) external nonReentrant {
        if (amount == 0) revert ZeroAmount();
        _settle(msg.sender);

        uint256 available = principalOf[msg.sender];
        if (amount > available) revert ExceedsPrincipal(amount, available);

        // Effects before interaction (checks-effects-interactions).
        principalOf[msg.sender] -= amount;
        totalPrincipal -= amount;

        // Interaction: pull USDC out of Aave directly to the user.
        strategy.withdraw(amount, msg.sender);

        emit Withdrawn(msg.sender, amount, block.timestamp);
    }

    /// @notice Sweep all harvestable yield to the treasury.
    ///         Permissionless: can only move surplus above total principal, never principal itself.
    function harvest() external nonReentrant {
        _accrue();
        uint256 amount = harvestable();
        if (amount < MIN_HARVEST) revert BelowMinHarvest();

        // bookedInAave fully exits to the treasury in this call.
        bookedInAave = 0;

        // Pull surplus from Aave directly to the treasury.
        strategy.withdraw(amount, treasury);

        // Solvency assertion: strategy must still cover all principal.
        if (strategy.totalAssets() < totalPrincipal) revert StrategyInsolvent();

        emit Harvested(amount, usdc.balanceOf(treasury));
    }

    // -------------------------------------------------------------------------
    // Views
    // -------------------------------------------------------------------------

    /// @notice Current redeemable USDC value held by the strategy.
    function totalAssets() public view returns (uint256) {
        return strategy.totalAssets();
    }

    /// @notice USDC surplus above total principal. Floored at zero; never reverts.
    function harvestable() public view returns (uint256) {
        uint256 assets = strategy.totalAssets();
        if (assets <= totalPrincipal) return 0;
        return assets - totalPrincipal;
    }

    /// @notice Exact cumulative USDC donated (or staged for donation) by `user`,
    ///         including live unbooked yield not yet reflected in donatedRealized.
    /// @dev This is the "you've donated $X" number shown in the UI.
    function donatedBy(address user) external view returns (uint256) {
        uint256 accLive = accDonatedPerPrincipal;
        if (totalPrincipal > 0) {
            uint256 assets = strategy.totalAssets();
            if (assets > totalPrincipal + bookedInAave) {
                uint256 newYield = assets - totalPrincipal - bookedInAave;
                accLive += (newYield * 1e27) / totalPrincipal;
            }
        }
        uint256 pending = (principalOf[user] * (accLive - donationCheckpoint[user])) / 1e27;
        return donatedRealized[user] + pending;
    }

    /// @notice USDC the user's current stake would donate over one year at the current yield rate.
    /// @dev    Rate in ray (1e27) from the strategy. Projection only; not a guarantee.
    function projectedAnnualDonation(address user) external view returns (uint256) {
        return (principalOf[user] * strategy.currentRateRay()) / 1e27;
    }

    // -------------------------------------------------------------------------
    // Governance / admin
    // -------------------------------------------------------------------------

    /// @notice Migrate to a new yield strategy. Moves all funds from old to new.
    /// @dev    Accrues yield before migration so no attribution is lost.
    function setStrategy(IYieldStrategy newStrategy) external onlyOwner {
        if (address(newStrategy) == address(0)) revert ZeroAddress();
        _accrue();

        IYieldStrategy old = strategy;
        uint256 assets = old.totalAssets();

        // Migrate: pull everything from old strategy to vault, then push to new.
        if (assets > 0) {
            old.withdraw(assets, address(this));
            usdc.forceApprove(address(newStrategy), assets);
            newStrategy.deposit(assets);
        }

        strategy = newStrategy;

        // Post-migration solvency check.
        if (newStrategy.totalAssets() < totalPrincipal) revert NewStrategyInsolvent();

        emit StrategySet(address(old), address(newStrategy));
    }

    /// @notice Update the treasury address.
    function setTreasury(address newTreasury) external onlyOwner {
        if (newTreasury == address(0)) revert ZeroAddress();
        emit TreasurySet(treasury, newTreasury);
        treasury = newTreasury;
    }

    /// @notice Pause deposits and harvests (withdrawals remain open).
    function pause() external onlyOwner {
        _pause();
    }

    /// @notice Unpause.
    function unpause() external onlyOwner {
        _unpause();
    }
}
